[project]
name = "neo-patrol-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "colorlog>=6.12.0",
    "matplotlib>=3.10.9",
    "mediapipe>=1.0.0",
    "onvif-python>=0.2.10",
    "opencv-python",
    "python-dotenv>=1.2.2",
    "pytz>=2026.3.post1",
    "yt-dlp>=2026.7.4",
]

[tool.uv.sources]
opencv-python = { path = "wheels/pc-x86_64/opencv_python-4.13.0.92-cp310-cp310-linux_x86_64.whl" }

[tool.uv]
override-dependencies = [
    "opencv-contrib-python ; python_version < '3.0'",
]
